### PR TITLE
林孟達develop PR

### PR DESCRIPTION
**Pull request by jason407891**
[http://52.64.152.248:5000/api/attractions?page=5](http://52.64.152.248:5000/api/attractions?page=5)
[http://52.64.152.248:5000/api/attractions?page=0&keyword=劍潭](http://52.64.152.248:5000/api/attractions?page=5&keyword=劍潭)
[http://52.64.152.248:5000/api/attractions?page=0&keyword=北](http://52.64.152.248:5000/api/attractions?page=5&keyword=北)
[http://52.64.152.248:5000/api/attraction/10](http://52.64.152.248:5000/api/attraction/10)
[http://52.64.152.248:5000/api//mrts](http://52.64.152.248:5000/api/mrts)

姓名: 林孟達

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. `images` field of attraction should be a string array containing every image URLs. For example: ["Image URL 1", "Image URL 2", ...]. But yours, for example, response of http://52.64.152.248:5000/api/attraction/10 is actually a string "['Image URL 1', 'Image URL 2', ...]"
2. `/api/attractions` is totally wrong obviously.
3. Response format of http://52.64.152.248:5000/api/mrts is incorrect.

Fix issues and re-request review.

**Comment by jason407891** [comment]
i have fixed the bug, please help to review again, thank you!

**Comment by cwpeng** [comment]
Re-request review from top right corner in this pull request, so that I can review for you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Always use second parameter of execute method to integrate variable into SQL query to prevent SQL injection.

Re-request review after you fixed this issue.

**Review by cwpeng — CHANGES_REQUESTED** [review]
The same issue remains. You should keep it in mind, review all code, and fix every related part.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
